name: Continuous update

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  continuous-update:
    name: Continuous update
    runs-on: macos-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Bump formula and cask
        env:
          HOMEBREW: |
            {
              "formula": [
                "spotctl"
              ],
              "cask": [
                "dupeguru-reference-modifier",
                "snail"
              ]
            }
        run: |
          for i in $(jq -r 'keys[]' <<< $HOMEBREW); do
            for j in $(jq -r ".$i[]" <<< $HOMEBREW); do
              bump=$(brew bump "--$i" $j)
              current=$(grep -E "^Current $i version" <<< "$bump" | sed -e 's|^.*: *||')
              latest=$(grep -E '^Latest livecheck version' <<< "$bump" | sed -e 's|^.*: *||')
              if [ "$current" != "$latest" ]; then
                brew "bump-$i-pr" --write-only --version="$latest" $j
              fi
            done
          done
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: continuous-update/${{steps.date.outputs.date}}
          branch-suffix: timestamp
          delete-branch: true
          commit-message: Update on ${{steps.date.outputs.date}}
          title: Continuous update on ${{steps.date.outputs.date}}
          body: |
            Auto-generated by `create-pull-request`[^1].

            [^1]: https://github.com/peter-evans/create-pull-request
          assignees: |
            silver886
          reviewers: |
            silver886
